version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
      - ./public:/app/public

  backend:
    build:
      context: ./Models
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Models:/app
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000 